### PR TITLE
Fix inconsistent spelling

### PR DESCRIPTION
**Pull request by visiblyisabelle**
s/color/colour

### CODE REVIEW

**Comment by SamboyCoding** [comment]
Where is it inconsistent

**Comment by visiblyisabelle** [comment]
Some strings used "colour" and some used "color", so for consistency I used the correct spelling.

**Comment by SamboyCoding** [comment]
The code base is localised en-US so if you change this to match that I'll accept it.

**Comment by visiblyisabelle** [comment]
no lol

**Comment by visiblyisabelle** [comment]
(please specify that in the language data filenames)

**Comment by SamboyCoding** [comment]
If and when I make a British English translation I will split out the filenames.

**Pull request closed without merging**
